"""
Writes parametric filters into Equalizer APO's config.txt. Equalizer APO
watches this file and hot-reloads it, which is what actually gives you
near-zero-latency EQ changes -- this module never touches audio directly.

IMPORTANT: verify this path matches your install. Default is usually:
C:\\Program Files\\EqualizerAPO\\config\\config.txt
"""

import os
import time
import threading

APO_CONFIG_PATH = r"C:\Program Files\EqualizerAPO\config\config.txt"

# Guards config.txt writes so an interpolation in flight from a previous
# write_filters() call can't race a newer one and clobber it out of order.
_write_lock = threading.Lock()
_write_generation = 0

def _write_file(filters, path):
    lines = ["# Auto-generated by EQ agent -- do not edit manually\n"]
    for freq, gain, q in filters:
        lines.append(f"Filter: ON PK Fc {freq} Hz Gain {gain:.1f} dB Q {q:.2f}\n")

    tmp_path = path + ".tmp"
    with open(tmp_path, "w") as f:
        f.writelines(lines)
    os.replace(tmp_path, path)

def _interpolate_and_write(old_filters, new_filters, path, generation):
    steps = 10
    sleep_time = 0.5 / steps

    # Assuming old_filters and new_filters have same structure/frequencies
    for i in range(1, steps + 1):
        with _write_lock:
            # A newer write_filters() call superseded us -- stop stepping so
            # we don't overwrite its (more current) result out of order.
            if generation != _write_generation:
                return
            t = i / steps
            interpolated = []
            for (f_old, g_old, q_old), (f_new, g_new, q_new) in zip(old_filters, new_filters):
                # We only interpolate gain for now to avoid weird frequency sweeps
                g = g_old + (g_new - g_old) * t
                interpolated.append((f_new, g, q_new))

            _write_file(interpolated, path)
        time.sleep(sleep_time)

def write_filters(filters, path: str = APO_CONFIG_PATH, old_filters=None):
    """filters: list of (freq_hz, gain_db, q) tuples."""
    global _write_generation
    with _write_lock:
        _write_generation += 1
        generation = _write_generation

    if old_filters is not None and len(old_filters) == len(filters):
        # Fire off interpolation in a background thread so we don't block.
        # generation lets a later call preempt an in-flight interpolation
        # instead of racing it for the final file write.
        t = threading.Thread(target=_interpolate_and_write, args=(old_filters, filters, path, generation))
        t.start()
    else:
        with _write_lock:
            if generation == _write_generation:
                _write_file(filters, path)
